name: Check branch fast-forward-ness

on:
  pull_request:
    branches: [master]

jobs:
  check-fast-forward-ness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ViRGiL175/check-branch-fast-forward-ness@main
        continue-on-error: true
